import os

YOUTUBE_API_KEY = os.environ["YOUTUBE_API_KEY"]
CONSUMER_SECRET = os.environ["CONSUMER_SECRET"]
CONSUMER_KEY = os.environ["CONSUMER_KEY"]
ACCESS_TOKEN = os.environ["ACCESS_TOKEN"]
ACCESS_TOKEN_SECRET = os.environ["ACCESS_TOKEN_SECRET"]
